import { Router } from "express";
import { authRouter } from "./auth.js";
import { healthRouter } from "./health.js";
import { courtsRouter } from "./courts.js";
import { bookingsRouter } from "./bookings.js";
import { customersRouter } from "./customers.js";
import { paymentsRouter } from "./payments.js";
import { membershipsRouter } from "./memberships.js";
import { promotionsRouter } from "./promotions.js";
import { calendarRouter } from "./calendar.js";
import { coachingRouter } from "./coaching.js";
import { equipmentRouter } from "./equipment.js";
import { productsRouter } from "./products.js";
import { expensesRouter } from "./expenses.js";
import { reportsRouter } from "./reports.js";
import { notificationsRouter } from "./notifications.js";
import { adminRouter } from "./admin.js";
import { profileRouter } from "./profile.js";
import { tournamentsRouter } from "./tournaments.js";
import { settingsRouter } from "./settings.js";
import { growthRouter } from "./growth.js";

export const apiRouter = Router();
apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/courts", courtsRouter);
apiRouter.use("/bookings", bookingsRouter);
apiRouter.use("/customers", customersRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/memberships", membershipsRouter);
apiRouter.use("/promotions", promotionsRouter);
apiRouter.use("/calendar", calendarRouter);
apiRouter.use("/coaching", coachingRouter);
apiRouter.use("/equipment", equipmentRouter);
apiRouter.use("/products", productsRouter);
apiRouter.use("/expenses", expensesRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/profile", profileRouter);
apiRouter.use("/tournaments", tournamentsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/growth", growthRouter);
