import { Router } from "express";
import { z } from "zod";
import { prisma } from "../db.js";
import { authenticate, authorize } from "../middleware/auth.js";
import { AppError } from "../utils/errors.js";

export const equipmentRouter = Router();
equipmentRouter.get("/manage", authenticate, authorize("SUPER_ADMIN", "ADMIN", "STAFF"), async (_req, res, next) => { try { const equipment = await prisma.equipment.findMany({ orderBy: { name: "asc" } }); res.json({ success: true, data: { equipment: equipment.map((item) => ({ ...item, rentalPrice: Number(item.rentalPrice) })) } }); } catch (error) { next(error); } });
equipmentRouter.get("/", async (_req, res, next) => { try { const equipment = await prisma.equipment.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }); res.json({ success: true, data: { equipment: equipment.map((item) => ({ ...item, rentalPrice: Number(item.rentalPrice) })) } }); } catch (error) { next(error); } });
equipmentRouter.use(authenticate);
equipmentRouter.get("/rentals", async (req, res, next) => { try { const isOperations = req.auth!.roles.some((role) => ["SUPER_ADMIN", "ADMIN", "STAFF"].includes(role)); const customer = isOperations ? null : await prisma.customer.findUnique({ where: { userId: req.auth!.userId } }); if (!isOperations && !customer) throw new AppError(403, "Rental history is only available to customers and authorized operations staff."); const rentals = await prisma.equipmentRental.findMany({ where: customer ? { customerId: customer.id } : {}, include: { equipment: true, customer: { include: { user: { select: { firstName: true, lastName: true } } } } }, orderBy: { startsAt: "desc" } }); res.json({ success: true, data: { rentals: rentals.map((rental) => ({ ...rental, unitPrice: Number(rental.unitPrice), startsAt: rental.startsAt.toISOString(), endsAt: rental.endsAt.toISOString(), returnedAt: rental.returnedAt?.toISOString() ?? null })) } }); } catch (error) { next(error); } });
equipmentRouter.post("/rentals", async (req, res, next) => { try { const input = z.object({ equipmentId: z.string(), quantity: z.coerce.number().int().positive(), bookingId: z.string(), startsAt: z.coerce.date(), endsAt: z.coerce.date() }).parse(req.body); const customer = await prisma.customer.findUnique({ where: { userId: req.auth!.userId } }); if (!customer) throw new AppError(403, "Customer profile not found."); const rental = await prisma.$transaction(async (tx) => { const booking = await tx.booking.findFirst({ where: { id: input.bookingId, customerId: customer.id, status: { in: ["PENDING", "CONFIRMED"] }, endsAt: { gt: new Date() } } }); if (!booking) throw new AppError(404, "Select one of your upcoming bookings for this rental."); const item = await tx.equipment.findUnique({ where: { id: input.equipmentId } }); if (!item || item.status !== "ACTIVE") throw new AppError(404, "Equipment not found."); const updated = await tx.equipment.updateMany({ where: { id: item.id, availableQuantity: { gte: input.quantity } }, data: { availableQuantity: { decrement: input.quantity } } }); if (updated.count !== 1) throw new AppError(409, "Not enough equipment is available."); return tx.equipmentRental.create({ data: { equipmentId: input.equipmentId, bookingId: booking.id, quantity: input.quantity, startsAt: booking.startsAt, endsAt: booking.endsAt, customerId: customer.id, unitPrice: item.rentalPrice }, include: { equipment: true } }); }); res.status(201).json({ success: true, data: { rental: { ...rental, unitPrice: Number(rental.unitPrice) } } }); } catch (error) { next(error); } });
equipmentRouter.post("/rentals/:id/return", authorize("SUPER_ADMIN", "ADMIN", "STAFF"), async (req, res, next) => {
  try {
    const rentalId = String(req.params.id);
    const rental = await prisma.$transaction(async (tx) => {
      await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${rentalId}))`;
      const current = await tx.equipmentRental.findUnique({ where: { id: rentalId }, include: { equipment: true, customer: { include: { user: { select: { firstName: true, lastName: true } } } } } });
      if (!current) throw new AppError(404, "Equipment rental not found.");
      if (current.status !== "RESERVED") throw new AppError(409, "This equipment rental has already been returned or cancelled.");
      await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`equipment:${current.equipmentId}`}))`;
      await tx.equipment.update({ where: { id: current.equipmentId }, data: { availableQuantity: Math.min(current.equipment.quantity, current.equipment.availableQuantity + current.quantity) } });
      const updated = await tx.equipmentRental.update({ where: { id: current.id }, data: { status: "RETURNED", returnedAt: new Date() }, include: { equipment: true, customer: { include: { user: { select: { firstName: true, lastName: true } } } } } });
      await tx.auditLog.create({ data: { userId: req.auth!.userId, action: "EQUIPMENT_RETURNED", entity: "EquipmentRental", entityId: current.id, metadata: { equipmentId: current.equipmentId, quantity: current.quantity } } });
      return updated;
    });
    res.json({ success: true, data: { rental: { ...rental, unitPrice: Number(rental.unitPrice), startsAt: rental.startsAt.toISOString(), endsAt: rental.endsAt.toISOString(), returnedAt: rental.returnedAt?.toISOString() ?? null } } });
  } catch (error) { next(error); }
});
equipmentRouter.post("/", authorize("SUPER_ADMIN", "ADMIN", "STAFF"), async (req, res, next) => { try { const input = z.object({ name: z.string().trim().min(2).max(100), quantity: z.coerce.number().int().nonnegative(), rentalPrice: z.coerce.number().nonnegative(), status: z.enum(["ACTIVE", "MAINTENANCE", "INACTIVE"]).default("ACTIVE") }).parse(req.body); const item = await prisma.equipment.create({ data: { ...input, availableQuantity: input.quantity } }); res.status(201).json({ success: true, data: { equipment: { ...item, rentalPrice: Number(item.rentalPrice) } } }); } catch (error) { next(error); } });
equipmentRouter.patch("/:id", authorize("SUPER_ADMIN", "ADMIN", "STAFF"), async (req, res, next) => { try { const input = z.object({ name: z.string().trim().min(2).max(100).optional(), quantity: z.coerce.number().int().nonnegative().optional(), rentalPrice: z.coerce.number().nonnegative().optional(), status: z.enum(["ACTIVE", "MAINTENANCE", "INACTIVE"]).optional(), availableQuantity: z.coerce.number().int().nonnegative().optional() }).parse(req.body); const current = await prisma.equipment.findUnique({ where: { id: String(req.params.id) } }); if (!current) throw new AppError(404, "Equipment not found."); const nextQuantity = input.quantity ?? current.quantity; const availableQuantity = input.availableQuantity ?? Math.min(current.availableQuantity, nextQuantity); const item = await prisma.equipment.update({ where: { id: current.id }, data: { ...input, quantity: nextQuantity, availableQuantity }, }); res.json({ success: true, data: { equipment: { ...item, rentalPrice: Number(item.rentalPrice) } } }); } catch (error) { next(error); } });
