import { Router } from "express";
import { z } from "zod";
import { prisma } from "../db.js";
import { authenticate, authorize } from "../middleware/auth.js";
import { AppError } from "../utils/errors.js";

export const productsRouter = Router();
productsRouter.use(authenticate, authorize("SUPER_ADMIN", "ADMIN", "STAFF"));
const productInput = z.object({ sku: z.string().trim().min(2).max(50), name: z.string().trim().min(2).max(100), categoryId: z.string().optional(), description: z.string().trim().max(500).optional(), price: z.coerce.number().nonnegative(), cost: z.coerce.number().nonnegative().default(0), stock: z.coerce.number().int().nonnegative(), lowStockThreshold: z.coerce.number().int().nonnegative().default(5), status: z.enum(["ACTIVE", "INACTIVE"]).default("ACTIVE") });
productsRouter.get("/", async (_req, res, next) => { try { const products = await prisma.product.findMany({ include: { category: true }, orderBy: { name: "asc" } }); res.json({ success: true, data: { products: products.map((product) => ({ ...product, price: Number(product.price), cost: Number(product.cost) })) } }); } catch (error) { next(error); } });
productsRouter.get("/categories", async (_req, res, next) => { try { const categories = await prisma.productCategory.findMany({ orderBy: { name: "asc" } }); res.json({ success: true, data: { categories } }); } catch (error) { next(error); } });
productsRouter.post("/categories", async (req, res, next) => { try { const input = z.object({ name: z.string().trim().min(2).max(80) }).parse(req.body); const category = await prisma.productCategory.create({ data: input }); res.status(201).json({ success: true, data: { category } }); } catch (error) { next(error); } });
productsRouter.post("/", async (req, res, next) => { try { const product = await prisma.product.create({ data: productInput.parse(req.body), include: { category: true } }); res.status(201).json({ success: true, data: { product: { ...product, price: Number(product.price), cost: Number(product.cost) } } }); } catch (error) { next(error); } });
productsRouter.put("/:id", async (req, res, next) => { try { const product = await prisma.product.update({ where: { id: String(req.params.id) }, data: productInput.partial().parse(req.body), include: { category: true } }); res.json({ success: true, data: { product: { ...product, price: Number(product.price), cost: Number(product.cost) } } }); } catch (error) { next(error); } });
productsRouter.post("/sales", async (req, res, next) => { try { const input = z.object({ customerId: z.string().optional(), paymentMethod: z.enum(["CASH", "BANK_TRANSFER", "GCASH", "CARD", "ONLINE_PAYMENT"]), items: z.array(z.object({ productId: z.string(), quantity: z.coerce.number().int().positive() })).min(1) }).parse(req.body); const sale = await prisma.$transaction(async (tx) => { const products = await Promise.all(input.items.map((item) => tx.product.findUnique({ where: { id: item.productId } }))); if (products.some((product) => !product || product.status !== "ACTIVE")) throw new AppError(404, "One or more products were not found."); const lines = input.items.map((item, index) => { const product = products[index]!; return { productId: item.productId, quantity: item.quantity, unitPrice: Number(product.price), total: Number(product.price) * item.quantity }; }); for (const line of lines) { const result = await tx.product.updateMany({ where: { id: line.productId, stock: { gte: line.quantity } }, data: { stock: { decrement: line.quantity } } }); if (result.count !== 1) throw new AppError(409, "Insufficient product stock."); } const created = await tx.sale.create({ data: { customerId: input.customerId, paymentMethod: input.paymentMethod, total: lines.reduce((sum, line) => sum + line.total, 0), items: { create: lines } }, include: { items: { include: { product: true } } } }); return created; }); res.status(201).json({ success: true, data: { sale: { ...sale, total: Number(sale.total), items: sale.items.map((item) => ({ ...item, unitPrice: Number(item.unitPrice), total: Number(item.total) })) } } }); } catch (error) { next(error); } });
productsRouter.get("/sales", async (_req, res, next) => { try { const sales = await prisma.sale.findMany({ include: { items: { include: { product: true } }, customer: { include: { user: { select: { firstName: true, lastName: true } } } } }, orderBy: { createdAt: "desc" }, take: 100 }); res.json({ success: true, data: { sales: sales.map((sale) => ({ ...sale, total: Number(sale.total), items: sale.items.map((item) => ({ ...item, unitPrice: Number(item.unitPrice), total: Number(item.total) })) })) } }); } catch (error) { next(error); } });
