import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, ArrowUpRight, Bot, CalendarPlus, CircleDollarSign, Clock3, Gauge, PackagePlus, Sparkles, Trophy, UserRoundCheck, Users } from "lucide-react";
import { cloneElement, useState, type ReactElement, type ReactNode } from "react";
import { Button } from "../../components/Button";
import { apiFetch, ApiError } from "../../lib/api";
import type { AutomationCampaign, Court, GrowthInsights, League, OpenPlay, PackagePlan, PricingRule, WaitlistEntry } from "../../types";
import { dateTime, money, Status } from "./shared";

type ManageData = { waitlist: WaitlistEntry[]; openPlays: OpenPlay[]; packages: PackagePlan[]; pricingRules: PricingRule[]; leagues: League[]; campaigns: AutomationCampaign[] };
const tomorrow = () => { const date = new Date(Date.now() + 86_400_000); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); };

export function OwnerGrowth({ isAdmin }: { isAdmin: boolean }) {
  const client = useQueryClient(); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [openPlay, setOpenPlay] = useState({ courtId: "", title: "Social Doubles Open Play", startsAt: tomorrow(), endsAt: "", skillMin: "2", skillMax: "4", capacity: "4", pricePerPlayer: "225", competitive: false });
  const [packageForm, setPackageForm] = useState({ name: "", description: "", price: "", bookingCredits: "5", validityDays: "90" });
  const [pricing, setPricing] = useState({ name: "Weekday off-peak", courtId: "", weekday: "", startTime: "13:00", endTime: "16:00", adjustmentPercent: "-15", minimumLeadHours: "2", maximumLeadHours: "" });
  const [league, setLeague] = useState({ name: "", description: "", skillMin: "2", skillMax: "4", startsAt: tomorrow(), endsAt: "", maxPlayers: "24", entryFee: "500", status: "REGISTRATION_OPEN" });
  const [matchForm, setMatchForm] = useState({ leagueId: "", homeEntryId: "", awayEntryId: "", scheduledAt: tomorrow() });
  const [matchScores, setMatchScores] = useState<Record<string, { homeScore: string; awayScore: string }>>({});
  const [campaign, setCampaign] = useState({ name: "", kind: "WIN_BACK", subject: "Your next rally is waiting", message: "It has been a while since your last game. See current open plays and available courts.", actionUrl: "/app/growth", triggerDays: "30" });
  const manage = useQuery({ queryKey: ["growth-manage"], queryFn: () => apiFetch<ManageData>("/api/growth/manage") });
  const insights = useQuery({ queryKey: ["growth-insights"], queryFn: () => apiFetch<GrowthInsights>("/api/growth/insights"), enabled: isAdmin });
  const courts = useQuery({ queryKey: ["courts"], queryFn: () => apiFetch<{ courts: Court[] }>("/api/courts") });
  const action = useMutation({ mutationFn: ({ url, method = "POST", body }: { url: string; method?: "POST" | "PATCH"; body?: unknown }) => apiFetch(url, { method, body: JSON.stringify(body ?? {}) }), onSuccess: () => { setError(""); setMessage("Changes saved successfully."); void Promise.all([client.invalidateQueries({ queryKey: ["growth-manage"] }), client.invalidateQueries({ queryKey: ["growth-insights"] }), client.invalidateQueries({ queryKey: ["payments"] })]); }, onError: (exception) => setError(exception instanceof ApiError ? exception.message : "Unable to save this change.") });
  if (manage.isLoading) return <div className="rounded-3xl bg-white p-10 text-center text-ink/50">Loading growth operations…</div>;
  if (manage.isError) return <div className="rounded-3xl bg-white p-10 text-center text-red-700">Unable to load growth operations. Apply the latest database schema, then refresh.</div>;
  const metrics = insights.data?.metrics;

  function createOpenPlay() { action.mutate({ url: "/api/growth/open-plays", body: { ...openPlay, startsAt: new Date(openPlay.startsAt).toISOString(), endsAt: new Date(openPlay.endsAt).toISOString(), skillMin: Number(openPlay.skillMin), skillMax: Number(openPlay.skillMax), capacity: Number(openPlay.capacity), pricePerPlayer: Number(openPlay.pricePerPlayer) } }); }
  function createPackage() { action.mutate({ url: "/api/growth/packages", body: { ...packageForm, price: Number(packageForm.price), bookingCredits: Number(packageForm.bookingCredits), validityDays: Number(packageForm.validityDays) } }); }
  function createPricing() { action.mutate({ url: "/api/growth/pricing-rules", body: { ...pricing, courtId: pricing.courtId || null, weekday: pricing.weekday === "" ? null : Number(pricing.weekday), adjustmentPercent: Number(pricing.adjustmentPercent), minimumLeadHours: pricing.minimumLeadHours === "" ? null : Number(pricing.minimumLeadHours), maximumLeadHours: pricing.maximumLeadHours === "" ? null : Number(pricing.maximumLeadHours) } }); }
  function createLeague() { action.mutate({ url: "/api/growth/leagues", body: { ...league, startsAt: new Date(league.startsAt).toISOString(), endsAt: new Date(league.endsAt).toISOString(), skillMin: Number(league.skillMin), skillMax: Number(league.skillMax), maxPlayers: league.maxPlayers ? Number(league.maxPlayers) : null, entryFee: Number(league.entryFee) } }); }
  function scheduleMatch() { action.mutate({ url: `/api/growth/leagues/${matchForm.leagueId}/matches`, body: { homeEntryId: matchForm.homeEntryId, awayEntryId: matchForm.awayEntryId, scheduledAt: new Date(matchForm.scheduledAt).toISOString() } }); }
  function recordResult(matchId: string) { const score = matchScores[matchId]; action.mutate({ url: `/api/growth/league-matches/${matchId}/result`, body: { homeScore: Number(score?.homeScore), awayScore: Number(score?.awayScore) } }); }
  function createCampaign() { action.mutate({ url: "/api/growth/campaigns", body: { ...campaign, triggerDays: Number(campaign.triggerDays) } }); }

  return <div>
    <div><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Growth command center</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Fill courts. Automate retention.</h1><p className="mt-2 max-w-3xl text-ink/55">Manage demand recovery, open-play inventory, club credit, competitive programs, customer automation, and pricing from one workspace.</p></div>
    {message && <div className="mt-5 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {isAdmin && <><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleDollarSign} label="Waitlist revenue recovered" value={money(metrics?.waitlistRecoveredRevenue ?? 0)} /><Metric icon={Users} label="Waiting customers" value={String(metrics?.waitlistWaiting ?? 0)} /><Metric icon={Activity} label="Open-play revenue" value={money(metrics?.openPlayRevenue ?? 0)} /><Metric icon={UserRoundCheck} label="Guest leads" value={String(metrics?.guestLeads ?? 0)} /></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.4fr]"><section className="rounded-3xl bg-pine p-6 text-white"><div className="flex items-center gap-2 text-lime"><Sparkles size={18} /><p className="text-sm font-bold uppercase tracking-wider">Recommended actions</p></div><div className="mt-4 space-y-3">{insights.data?.recommendations.length ? insights.data.recommendations.map((item) => <div key={`${item.type}-${item.title}`} className="rounded-xl bg-white/10 p-4"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm leading-6 text-white/60">{item.message}</p></div>) : <p className="text-sm text-white/60">No urgent recommendations. Utilization is healthy.</p>}</div></section><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">30-day court utilization</h2><div className="mt-5 space-y-4">{insights.data?.utilization.map((court) => <div key={court.courtId}><div className="mb-1 flex justify-between text-sm"><span>{court.court}</span><strong>{court.utilizationPercent}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-sand"><div className="h-full rounded-full bg-pine" style={{ width: `${Math.min(100, court.utilizationPercent)}%` }} /></div></div>)}</div></section></div></>}

    <div className="mt-8 grid gap-8 xl:grid-cols-2">
      <Panel title="Open-play inventory" subtitle="Reserve a court and sell compatible player spots individually." icon={CalendarPlus}>
        {isAdmin && <div className="grid gap-3 sm:grid-cols-2"><Field label="Title"><input value={openPlay.title} onChange={(event) => setOpenPlay({ ...openPlay, title: event.target.value })} /></Field><Field label="Court"><select value={openPlay.courtId} onChange={(event) => setOpenPlay({ ...openPlay, courtId: event.target.value })}><option value="">Choose court</option>{courts.data?.courts.map((court) => <option key={court.id} value={court.id}>{court.name}</option>)}</select></Field><Field label="Starts"><input type="datetime-local" value={openPlay.startsAt} onChange={(event) => setOpenPlay({ ...openPlay, startsAt: event.target.value })} /></Field><Field label="Ends"><input type="datetime-local" value={openPlay.endsAt} onChange={(event) => setOpenPlay({ ...openPlay, endsAt: event.target.value })} /></Field><Field label="Skill minimum"><input type="number" step="0.1" value={openPlay.skillMin} onChange={(event) => setOpenPlay({ ...openPlay, skillMin: event.target.value })} /></Field><Field label="Skill maximum"><input type="number" step="0.1" value={openPlay.skillMax} onChange={(event) => setOpenPlay({ ...openPlay, skillMax: event.target.value })} /></Field><Field label="Capacity"><input type="number" value={openPlay.capacity} onChange={(event) => setOpenPlay({ ...openPlay, capacity: event.target.value })} /></Field><Field label="Price per player"><input type="number" value={openPlay.pricePerPlayer} onChange={(event) => setOpenPlay({ ...openPlay, pricePerPlayer: event.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={openPlay.competitive} onChange={(event) => setOpenPlay({ ...openPlay, competitive: event.target.checked })} />Competitive match</label><Button disabled={action.isPending || !openPlay.courtId || !openPlay.endsAt} onClick={createOpenPlay}>Create open play</Button></div>}
        <div className="mt-5 space-y-3">{manage.data?.openPlays.slice(0, 8).map((play) => <div key={play.id} className="rounded-xl bg-sand p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{play.title}</p><p className="text-xs text-ink/45">{play.court.name} · {dateTime(play.startsAt)}</p></div><Status value={play.status} /></div><p className="mt-2 text-sm text-ink/55">{play.participants.length}/{play.capacity} players · {money(play.pricePerPlayer)} each</p>{play.participants.filter((participant) => participant.status === "JOINED").map((participant) => <div key={participant.id} className="mt-2 flex items-center justify-between rounded-lg bg-white px-3 py-2 text-sm"><span>{participant.customer.user.firstName} {participant.customer.user.lastName}</span><Button className="px-3 py-2 text-xs" disabled={action.isPending} onClick={() => action.mutate({ url: `/api/growth/open-play-participants/${participant.id}/confirm` })}>Confirm payment</Button></div>)}</div>)}</div>
      </Panel>

      <Panel title="Waitlist recovery" subtitle="Monitor offered times and customers waiting for cancellations." icon={Clock3}>
        <div className="space-y-3">{manage.data?.waitlist.length ? manage.data.waitlist.slice(0, 12).map((entry) => <div key={entry.id} className="flex items-start justify-between gap-3 rounded-xl bg-sand p-4"><div><p className="font-semibold">{entry.court.name}</p><p className="mt-1 text-sm text-ink/55">{entry.customer?.user.firstName} {entry.customer?.user.lastName}</p><p className="mt-1 text-xs text-ink/40">{dateTime(entry.startsAt)} · {entry.durationMinutes} min</p></div><Status value={entry.status} /></div>) : <Empty text="No customers are waiting for a court." />}</div>
      </Panel>

      {isAdmin && <Panel title="Booking packages" subtitle="Create prepaid credits that confirm bookings instantly." icon={PackagePlus}>
        <div className="grid gap-3 sm:grid-cols-2"><Field label="Package name"><input value={packageForm.name} onChange={(event) => setPackageForm({ ...packageForm, name: event.target.value })} /></Field><Field label="Price"><input type="number" value={packageForm.price} onChange={(event) => setPackageForm({ ...packageForm, price: event.target.value })} /></Field><Field label="Booking credits"><input type="number" value={packageForm.bookingCredits} onChange={(event) => setPackageForm({ ...packageForm, bookingCredits: event.target.value })} /></Field><Field label="Validity days"><input type="number" value={packageForm.validityDays} onChange={(event) => setPackageForm({ ...packageForm, validityDays: event.target.value })} /></Field><Field label="Description" className="sm:col-span-2"><textarea value={packageForm.description} onChange={(event) => setPackageForm({ ...packageForm, description: event.target.value })} /></Field><Button className="sm:col-span-2" disabled={action.isPending || !packageForm.name || !packageForm.price} onClick={createPackage}>Create package</Button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{manage.data?.packages.map((plan) => <div key={plan.id} className="rounded-xl bg-sand p-4"><p className="font-semibold">{plan.name}</p><p className="mt-1 text-sm text-ink/50">{plan.bookingCredits} credits · {plan.validityDays} days</p><p className="mt-2 font-semibold">{money(plan.price)}</p></div>)}</div>
      </Panel>}

      {isAdmin && <Panel title="Revenue pricing rules" subtitle="Apply owner-controlled increases or discounts by court, day, time, and lead window." icon={Gauge}>
        <div className="grid gap-3 sm:grid-cols-2"><Field label="Rule name"><input value={pricing.name} onChange={(event) => setPricing({ ...pricing, name: event.target.value })} /></Field><Field label="Court"><select value={pricing.courtId} onChange={(event) => setPricing({ ...pricing, courtId: event.target.value })}><option value="">All courts</option>{courts.data?.courts.map((court) => <option key={court.id} value={court.id}>{court.name}</option>)}</select></Field><Field label="Day"><select value={pricing.weekday} onChange={(event) => setPricing({ ...pricing, weekday: event.target.value })}><option value="">Every day</option>{["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].map((day, index) => <option key={day} value={index}>{day}</option>)}</select></Field><Field label="Adjustment %"><input type="number" value={pricing.adjustmentPercent} onChange={(event) => setPricing({ ...pricing, adjustmentPercent: event.target.value })} /></Field><Field label="Start time"><input type="time" value={pricing.startTime} onChange={(event) => setPricing({ ...pricing, startTime: event.target.value })} /></Field><Field label="End time"><input type="time" value={pricing.endTime} onChange={(event) => setPricing({ ...pricing, endTime: event.target.value })} /></Field><Button className="sm:col-span-2" disabled={action.isPending} onClick={createPricing}>Create pricing rule</Button></div><div className="mt-4 space-y-2">{manage.data?.pricingRules.map((rule) => <div key={rule.id} className="flex items-center justify-between rounded-xl bg-sand p-3"><div><p className="font-medium">{rule.name}</p><p className="text-xs text-ink/45">{rule.court?.name ?? "All courts"} · {rule.startTime}–{rule.endTime}</p></div><button className={`rounded-lg px-3 py-2 text-sm font-semibold ${rule.isActive ? "bg-lime text-pine" : "bg-white text-ink/50"}`} onClick={() => action.mutate({ url: `/api/growth/pricing-rules/${rule.id}`, method: "PATCH", body: { isActive: !rule.isActive } })}>{rule.adjustmentPercent > 0 ? "+" : ""}{rule.adjustmentPercent}%</button></div>)}</div>
      </Panel>}

      {isAdmin && <Panel title="Leagues & local ratings" subtitle="Open a competitive division, confirm entries, and build standings." icon={Users}>
        <div className="grid gap-3 sm:grid-cols-2"><Field label="League name"><input value={league.name} onChange={(event) => setLeague({ ...league, name: event.target.value })} /></Field><Field label="Entry fee"><input type="number" value={league.entryFee} onChange={(event) => setLeague({ ...league, entryFee: event.target.value })} /></Field><Field label="Starts"><input type="datetime-local" value={league.startsAt} onChange={(event) => setLeague({ ...league, startsAt: event.target.value })} /></Field><Field label="Ends"><input type="datetime-local" value={league.endsAt} onChange={(event) => setLeague({ ...league, endsAt: event.target.value })} /></Field><Field label="Skill minimum"><input type="number" step="0.1" value={league.skillMin} onChange={(event) => setLeague({ ...league, skillMin: event.target.value })} /></Field><Field label="Skill maximum"><input type="number" step="0.1" value={league.skillMax} onChange={(event) => setLeague({ ...league, skillMax: event.target.value })} /></Field><Field label="Description" className="sm:col-span-2"><textarea value={league.description} onChange={(event) => setLeague({ ...league, description: event.target.value })} /></Field><Button className="sm:col-span-2" disabled={action.isPending || !league.name || !league.endsAt} onClick={createLeague}>Create league</Button></div><div className="mt-4 space-y-3">{manage.data?.leagues.map((item) => <div key={item.id} className="rounded-xl bg-sand p-4"><div className="flex justify-between"><p className="font-semibold">{item.name}</p><Status value={item.status} /></div><p className="mt-1 text-sm text-ink/50">{item.entries.length} entries · {item.skillMin.toFixed(1)}–{item.skillMax.toFixed(1)}</p>{item.entries.filter((entry) => entry.status === "PENDING").map((entry) => <div key={entry.id} className="mt-2 flex items-center justify-between rounded-lg bg-white px-3 py-2 text-sm"><span>{entry.customer.user.firstName} {entry.customer.user.lastName}</span><Button className="px-3 py-2 text-xs" onClick={() => action.mutate({ url: `/api/growth/league-entries/${entry.id}/confirm` })}>Confirm entry</Button></div>)}</div>)}</div>
      </Panel>}

      <Panel title="League match desk" subtitle="Schedule fixtures and record final scores; standings and local ratings update automatically." icon={Trophy}>
        {isAdmin && <div className="grid gap-3 sm:grid-cols-2"><Field label="League"><select value={matchForm.leagueId} onChange={(event) => setMatchForm({ ...matchForm, leagueId: event.target.value, homeEntryId: "", awayEntryId: "" })}><option value="">Choose league</option>{manage.data?.leagues.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Scheduled time"><input type="datetime-local" value={matchForm.scheduledAt} onChange={(event) => setMatchForm({ ...matchForm, scheduledAt: event.target.value })} /></Field><Field label="Home player"><select value={matchForm.homeEntryId} onChange={(event) => setMatchForm({ ...matchForm, homeEntryId: event.target.value })}><option value="">Choose player</option>{manage.data?.leagues.find((item) => item.id === matchForm.leagueId)?.entries.filter((entry) => entry.status === "ACTIVE").map((entry) => <option key={entry.id} value={entry.id}>{entry.customer.user.firstName} {entry.customer.user.lastName}</option>)}</select></Field><Field label="Away player"><select value={matchForm.awayEntryId} onChange={(event) => setMatchForm({ ...matchForm, awayEntryId: event.target.value })}><option value="">Choose player</option>{manage.data?.leagues.find((item) => item.id === matchForm.leagueId)?.entries.filter((entry) => entry.status === "ACTIVE").map((entry) => <option key={entry.id} value={entry.id}>{entry.customer.user.firstName} {entry.customer.user.lastName}</option>)}</select></Field><Button className="sm:col-span-2" disabled={action.isPending || !matchForm.leagueId || !matchForm.homeEntryId || !matchForm.awayEntryId || matchForm.homeEntryId === matchForm.awayEntryId} onClick={scheduleMatch}>Schedule match</Button></div>}
        <div className={isAdmin ? "mt-5 space-y-3" : "space-y-3"}>{manage.data?.leagues.flatMap((item) => item.matches.map((match) => { const home = item.entries.find((entry) => entry.id === match.homeEntryId); const away = item.entries.find((entry) => entry.id === match.awayEntryId); const score = matchScores[match.id] ?? { homeScore: "", awayScore: "" }; return <div key={match.id} className="rounded-xl bg-sand p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{home ? `${home.customer.user.firstName} ${home.customer.user.lastName}` : "Home player"} vs {away ? `${away.customer.user.firstName} ${away.customer.user.lastName}` : "Away player"}</p><p className="mt-1 text-xs text-ink/45">{item.name} · {dateTime(match.scheduledAt)}</p></div><Status value={match.status} /></div>{match.status === "SCHEDULED" && <div className="mt-3 grid grid-cols-[1fr_1fr_auto] gap-2"><input aria-label="Home score" type="number" min="0" placeholder="Home" value={score.homeScore} onChange={(event) => setMatchScores({ ...matchScores, [match.id]: { ...score, homeScore: event.target.value } })} className="min-w-0 rounded-lg border border-black/10 px-3 py-2 text-sm" /><input aria-label="Away score" type="number" min="0" placeholder="Away" value={score.awayScore} onChange={(event) => setMatchScores({ ...matchScores, [match.id]: { ...score, awayScore: event.target.value } })} className="min-w-0 rounded-lg border border-black/10 px-3 py-2 text-sm" /><Button className="px-3 py-2 text-xs" disabled={action.isPending || score.homeScore === "" || score.awayScore === "" || score.homeScore === score.awayScore} onClick={() => recordResult(match.id)}>Record</Button></div>}{match.status === "COMPLETED" && <p className="mt-3 text-sm font-semibold text-pine">Final score {match.homeScore}–{match.awayScore}</p>}</div>; }))}{!manage.data?.leagues.some((item) => item.matches.length > 0) && <Empty text="No league matches are scheduled." />}</div>
      </Panel>

      {isAdmin && <Panel title="Retention automation" subtitle="Send targeted in-app journeys daily without duplicate campaign runs." icon={Bot}>
        <div className="grid gap-3 sm:grid-cols-2"><Field label="Campaign name"><input value={campaign.name} onChange={(event) => setCampaign({ ...campaign, name: event.target.value })} /></Field><Field label="Audience trigger"><select value={campaign.kind} onChange={(event) => setCampaign({ ...campaign, kind: event.target.value })}><option value="WIN_BACK">Inactive players</option><option value="MEMBERSHIP_EXPIRY">Expiring memberships</option><option value="BIRTHDAY">Upcoming birthdays</option><option value="PROMOTION">All opted-in players</option></select></Field><Field label="Notification title"><input value={campaign.subject} onChange={(event) => setCampaign({ ...campaign, subject: event.target.value })} /></Field><Field label="Trigger days"><input type="number" value={campaign.triggerDays} onChange={(event) => setCampaign({ ...campaign, triggerDays: event.target.value })} /></Field><Field label="Message" className="sm:col-span-2"><textarea value={campaign.message} onChange={(event) => setCampaign({ ...campaign, message: event.target.value })} /></Field><Button className="sm:col-span-2" disabled={action.isPending || !campaign.name} onClick={createCampaign}>Create automation</Button></div><div className="mt-4 space-y-2">{manage.data?.campaigns.map((item) => <div key={item.id} className="flex flex-col justify-between gap-3 rounded-xl bg-sand p-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><p className="font-semibold">{item.name}</p><Status value={item.status} /></div><p className="mt-1 text-xs text-ink/45">{item.kind.replaceAll("_", " ")} · last run {item.lastRunAt ? new Date(item.lastRunAt).toLocaleString("en-PH") : "never"}</p></div><div className="flex gap-2"><Button variant="ghost" className="px-3 py-2 text-xs" onClick={() => action.mutate({ url: `/api/growth/campaigns/${item.id}`, method: "PATCH", body: { status: item.status === "ACTIVE" ? "PAUSED" : "ACTIVE" } })}>{item.status === "ACTIVE" ? "Pause" : "Activate"}</Button><Button className="px-3 py-2 text-xs" disabled={item.status !== "ACTIVE"} onClick={() => action.mutate({ url: `/api/growth/campaigns/${item.id}/run` })}>Run now <ArrowUpRight className="ml-1 inline" size={13} /></Button></div></div>)}</div>
      </Panel>}
    </div>
  </div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <div className="rounded-2xl bg-white p-5 shadow-sm"><Icon className="text-pine" size={20} /><p className="mt-4 text-sm text-ink/45">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>; }
function Panel({ title, subtitle, icon: Icon, children }: { title: string; subtitle: string; icon: typeof Activity; children: ReactNode }) { return <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-lime text-pine"><Icon size={19} /></div><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-ink/50">{subtitle}</p></div></div>{children}</section>; }
function Field({ label, className = "", children }: { label: string; className?: string; children: ReactElement<{ className?: string }> }) { return <label className={`text-sm font-medium ${className}`}>{label}{cloneElement(children, { className: `mt-1.5 min-h-11 w-full rounded-xl border border-black/10 bg-white px-3 py-2.5 text-sm outline-none ${children.props.className ?? ""}` })}</label>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-sand p-6 text-center text-sm text-ink/45">{text}</p>; }
