import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, UserRound } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "../components/Button";
import { apiFetch, ApiError } from "../lib/api";
import type { Coach } from "../types";

const empty = { biography: "", experience: "", certifications: "", hourlyRate: "900", status: "ACTIVE" };

export function CoachManagement() {
  const client = useQueryClient();
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [editing, setEditing] = useState<Coach | null>(null);
  const [form, setForm] = useState(empty);
  const query = useQuery({ queryKey: ["manage-coaches"], queryFn: () => apiFetch<{ coaches: Coach[] }>("/api/coaching/manage") });
  const save = useMutation({ mutationFn: () => apiFetch(`/api/coaching/manage/${editing?.id}`, { method: "PATCH", body: JSON.stringify({ ...form, hourlyRate: Number(form.hourlyRate) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["manage-coaches"] }); setEditing(null); setForm(empty); setMessage("Coach profile updated."); } });
  function edit(coach: Coach) { setEditing(coach); setForm({ biography: coach.biography ?? "", experience: coach.experience ?? "", certifications: coach.certifications ?? "", hourlyRate: String(coach.hourlyRate), status: coach.status }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); try { await save.mutateAsync(); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to save coach."); } }

  return <div><div><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Coaches</h1><p className="mt-2 text-ink/55">Create coach accounts under Users, then maintain public profiles, rates, and availability here.</p></div>{message && <div className="mt-5 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {editing && <form onSubmit={submit} className="mt-6 grid gap-4 rounded-3xl bg-white p-6 md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-lg font-semibold">Edit {editing.user.firstName} {editing.user.lastName}</h2></div><label className="text-sm font-medium">Hourly rate<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="0" step="0.01" value={form.hourlyRate} onChange={(event) => setForm({ ...form, hourlyRate: event.target.value })} /></label><label className="text-sm font-medium">Status<select className="mt-1.5 w-full rounded-xl border border-black/10 bg-white px-3 py-3" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label className="text-sm font-medium md:col-span-2">Biography<textarea className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" rows={3} value={form.biography} onChange={(event) => setForm({ ...form, biography: event.target.value })} /></label><label className="text-sm font-medium">Experience<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.experience} onChange={(event) => setForm({ ...form, experience: event.target.value })} /></label><label className="text-sm font-medium">Certifications<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.certifications} onChange={(event) => setForm({ ...form, certifications: event.target.value })} /></label><div className="flex gap-2 md:col-span-2"><Button disabled={save.isPending}>{save.isPending ? "Saving…" : "Save changes"}</Button><Button type="button" variant="ghost" onClick={() => setEditing(null)}>Cancel</Button></div></form>}
    {query.isLoading ? <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">Loading coaches…</div> : query.isError ? <div className="mt-6 rounded-3xl bg-red-50 p-10 text-center text-sm text-red-700">Unable to load coaches.</div> : query.data?.coaches.length ? <div className="mt-6 grid gap-4 md:grid-cols-2">{query.data.coaches.map((coach) => <div key={coach.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-lime text-pine"><UserRound size={19} /></div><div className="min-w-0"><p className="truncate font-semibold">{coach.user.firstName} {coach.user.lastName}</p><p className="truncate text-sm text-ink/50">{coach.user.email}</p></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${coach.status === "ACTIVE" ? "bg-lime/60 text-pine" : "bg-black/5 text-ink/45"}`}>{coach.status}</span></div><p className="mt-4 text-sm leading-6 text-ink/60">{coach.biography || "No biography yet."}</p><p className="mt-3 text-sm font-semibold">₱{coach.hourlyRate.toLocaleString()}/hour</p><button className="mt-4 text-sm font-semibold text-pine" onClick={() => edit(coach)}><Pencil className="mr-1 inline" size={15} />Edit profile</button></div>)}</div> : <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">No coach accounts exist. <Link className="font-semibold text-pine underline" to="/app/users">Create a coach user</Link>.</div>}
  </div>;
}
