import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, ImagePlus, Pencil, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { Button } from "../components/Button";
import { apiFetch, ApiError } from "../lib/api";
import type { Court } from "../types";
import { createImageCropSource, ImageCropDialog, type ImageCropSource } from "../components/ImageCropDialog";

type CourtForm = { name: string; description: string; location: string; indoor: boolean; surfaceType: string; status: string; openingTime: string; closingTime: string; hourlyRate: string; imageUrl: string; features: string };
const empty: CourtForm = { name: "", description: "", location: "", indoor: true, surfaceType: "Acrylic", status: "AVAILABLE", openingTime: "06:00", closingTime: "22:00", hourlyRate: "500", imageUrl: "", features: "" };
const courtImageWidth = 1280;
const courtImageHeight = 720;
const maximumCourtImageBytes = 650 * 1024;
const maximumSourceCourtImageBytes = 12 * 1024 * 1024;

export function CourtManagement() {
  const client = useQueryClient();
  const [form, setForm] = useState<CourtForm>(empty);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [cropSource, setCropSource] = useState<ImageCropSource | null>(null);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const query = useQuery({ queryKey: ["courts"], queryFn: () => apiFetch<{ courts: Court[] }>("/api/courts") });
  const save = useMutation({ mutationFn: () => apiFetch<{ court: Court }>(editingId ? `/api/courts/${editingId}` : "/api/courts", { method: editingId ? "PUT" : "POST", body: JSON.stringify({ ...form, hourlyRate: Number(form.hourlyRate), imageUrl: form.imageUrl, features: form.features.split(",").map((feature) => feature.trim()).filter(Boolean) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["courts"] }); setForm(empty); setEditingId(null); setCropSource(null); setMessage("Court saved successfully."); } });
  const remove = useMutation({ mutationFn: (id: string) => apiFetch<{ court: Court }>(`/api/courts/${id}`, { method: "DELETE" }), onSuccess: () => client.invalidateQueries({ queryKey: ["courts"] }) });
  function edit(court: Court) { setEditingId(court.id); setCropSource(null); setForm({ name: court.name, description: court.description ?? "", location: court.location ?? "", indoor: court.indoor, surfaceType: court.surfaceType ?? "", status: court.status, openingTime: court.openingTime, closingTime: court.closingTime, hourlyRate: String(court.hourlyRate), imageUrl: court.imageUrl ?? "", features: Array.isArray(court.features) ? court.features.filter((feature): feature is string => typeof feature === "string").join(", ") : "" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); if (form.closingTime <= form.openingTime) { setError("Closing time must be after opening time."); return; } try { await save.mutateAsync(); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to save court."); } }
  async function chooseCourtImage(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setError(""); setMessage(""); try { setCropSource(await createImageCropSource(file, maximumSourceCourtImageBytes)); } catch (exception) { setError(exception instanceof Error ? exception.message : "Unable to use this court image."); } }

  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Courts</h1><p className="mt-2 text-ink/55">Manage availability, operating hours, pricing, surfaces, and public court details.</p></div><Button variant="secondary" onClick={() => { setEditingId(null); setCropSource(null); setForm(empty); }}><Plus className="mr-1 inline" size={16} />New court</Button></div>
    {message && <div className="mt-5 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <form onSubmit={submit} className="mt-6 grid gap-4 rounded-3xl bg-white p-6 shadow-sm md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-lg font-semibold">{editingId ? "Edit court" : "Add court"}</h2></div>
      <label className="text-sm font-medium">Court name<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label>
      <label className="text-sm font-medium">Location<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} /></label>
      <label className="text-sm font-medium">Surface type<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.surfaceType} onChange={(event) => setForm({ ...form, surfaceType: event.target.value })} placeholder="Acrylic, concrete, wood" /></label>
      <label className="text-sm font-medium">Status<select className="mt-1.5 w-full rounded-xl border border-black/10 bg-white px-3 py-3" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="AVAILABLE">Available</option><option value="MAINTENANCE">Maintenance</option><option value="CLOSED">Closed</option></select></label>
      <label className="text-sm font-medium md:col-span-2">Description<textarea className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" rows={2} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label>
      <label className="text-sm font-medium">Hourly rate<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="0" step="0.01" value={form.hourlyRate} onChange={(event) => setForm({ ...form, hourlyRate: event.target.value })} required /></label>
      <label className="flex items-center gap-2 pt-7 text-sm font-medium"><input type="checkbox" checked={form.indoor} onChange={(event) => setForm({ ...form, indoor: event.target.checked })} /> Indoor court</label>
      <label className="text-sm font-medium">Opening time<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="time" value={form.openingTime} onChange={(event) => setForm({ ...form, openingTime: event.target.value })} required /></label>
      <label className="text-sm font-medium">Closing time<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="time" value={form.closingTime} onChange={(event) => setForm({ ...form, closingTime: event.target.value })} required /></label>
      <div className="rounded-2xl border border-black/5 bg-sand/70 p-4 md:col-span-2"><div className="grid gap-4 sm:grid-cols-[minmax(0,320px)_1fr] sm:items-center"><div className="aspect-video overflow-hidden rounded-2xl bg-pine shadow-sm">{form.imageUrl ? <img src={form.imageUrl} alt="Court banner preview" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-center text-sm font-semibold text-white/70"><span><Building2 className="mx-auto mb-2" size={28} />No court image selected</span></div>}</div><div><p className="text-sm font-semibold">Court banner image</p><p className="mt-1 text-xs leading-5 text-ink/50">Choose any regular photo up to 12 MB. Crop and reposition it here; the system creates an optimized 1280×720 WebP banner.</p><div className="mt-4 flex flex-wrap gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-pine px-4 py-2.5 text-sm font-semibold text-white"><ImagePlus size={16} />{form.imageUrl ? "Replace and crop" : "Choose and crop image"}<input className="sr-only" type="file" accept="image/*" onChange={(event) => void chooseCourtImage(event)} /></label>{form.imageUrl && <Button type="button" variant="ghost" onClick={() => setForm({ ...form, imageUrl: "" })}><Trash2 className="mr-1 inline" size={16} />Remove image</Button>}</div></div></div></div>
      <label className="text-sm font-medium md:col-span-2">Features (comma separated)<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.features} onChange={(event) => setForm({ ...form, features: event.target.value })} placeholder="Lighting, spectator seating, water station" /></label>
      <div className="flex gap-2 md:col-span-2"><Button disabled={save.isPending}>{save.isPending ? "Saving…" : editingId ? "Save changes" : "Create court"}</Button>{editingId && <Button type="button" variant="ghost" onClick={() => { setEditingId(null); setCropSource(null); setForm(empty); }}>Cancel</Button>}</div>
    </form>
    {query.isLoading ? <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">Loading courts…</div> : query.isError ? <div className="mt-6 rounded-3xl bg-red-50 p-10 text-center text-sm text-red-700">Unable to load courts.</div> : query.data?.courts.length ? <div className="mt-6 grid gap-4 md:grid-cols-2">{query.data.courts.map((court) => <div key={court.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-lime text-pine"><Building2 size={20} /></div><div><h2 className="font-semibold">{court.name}</h2><p className="text-sm text-ink/50">{court.location || "No location"} · {court.surfaceType || "Surface not set"}</p></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${court.status === "AVAILABLE" ? "bg-lime/60 text-pine" : "bg-red-50 text-red-700"}`}>{court.status}</span></div><div className="mt-5 flex justify-between text-sm text-ink/55"><span>{court.openingTime}–{court.closingTime}</span><span>₱{court.hourlyRate.toLocaleString()}/hr</span></div><div className="mt-5 flex gap-3 border-t border-black/5 pt-4"><button className="text-sm font-semibold text-pine" onClick={() => edit(court)}><Pencil className="mr-1 inline" size={15} />Edit</button><button className="text-sm font-semibold text-red-600" onClick={() => { if (window.confirm(`Deactivate ${court.name}?`)) void remove.mutateAsync(court.id); }}><Trash2 className="mr-1 inline" size={15} />Deactivate</button></div></div>)}</div> : <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">No courts have been created.</div>}
    {cropSource && <ImageCropDialog source={cropSource} eyebrow="Court image editor" title="Crop and position the court banner" outputWidth={courtImageWidth} outputHeight={courtImageHeight} maximumOutputBytes={maximumCourtImageBytes} previewDescription="Everything inside this 16:9 frame appears in the public court banner." onCancel={() => setCropSource(null)} onApply={(output) => { setForm((current) => ({ ...current, imageUrl: output })); setCropSource(null); setMessage("Cropped 1280×720 court image ready. Save the court to publish it."); }} />}
  </div>;
}
