import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, Search, Trash2, UserPlus, X } from "lucide-react";
import { useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { Button } from "../components/Button";
import { apiFetch, ApiError } from "../lib/api";
import type { Customer } from "../types";

type Form = { firstName: string; lastName: string; email: string; phone: string; address: string; notes: string; password: string };
const empty: Form = { firstName: "", lastName: "", email: "", phone: "", address: "", notes: "", password: "" };

export function Customers() {
  const { user } = useAuth();
  const client = useQueryClient();
  const canDeactivate = user?.roles.some((role) => ["SUPER_ADMIN", "ADMIN"].includes(role)) ?? false;
  const [search, setSearch] = useState("");
  const [form, setForm] = useState<Form>(empty);
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Customer | null>(null);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const query = useQuery({ queryKey: ["customers", search], queryFn: () => apiFetch<{ customers: Customer[] }>(`/api/customers?search=${encodeURIComponent(search)}`) });
  const save = useMutation({ mutationFn: () => apiFetch<{ customer: Customer }>(editing ? `/api/customers/${editing.id}` : "/api/customers", { method: editing ? "PUT" : "POST", body: JSON.stringify({ ...form, password: form.password || undefined }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["customers"] }); closeForm(); setMessage(editing ? "Customer updated." : "Customer registered."); } });
  const deactivate = useMutation({ mutationFn: (id: string) => apiFetch(`/api/customers/${id}`, { method: "DELETE" }), onSuccess: () => { client.invalidateQueries({ queryKey: ["customers"] }); setMessage("Customer deactivated."); } });
  function closeForm() { setOpen(false); setEditing(null); setForm(empty); }
  function editCustomer(customer: Customer) { setEditing(customer); setForm({ firstName: customer.firstName, lastName: customer.lastName, email: customer.email, phone: customer.phone ?? "", address: customer.address ?? "", notes: customer.notes ?? "", password: "" }); setOpen(true); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); if (!editing && form.password.length < 8) { setError("Set a temporary password with at least 8 characters."); return; } try { await save.mutateAsync(); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to save customer."); } }

  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Customers</h1><p className="mt-2 text-ink/55">Search and maintain customer contact details, memberships, and booking activity.</p></div><Button variant="secondary" onClick={() => { setEditing(null); setForm(empty); setOpen(true); }}><UserPlus className="mr-1 inline" size={16} />Register customer</Button></div>
    {message && <div className="mt-5 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <div className="mt-6 flex items-center gap-3 rounded-2xl bg-white px-4 py-3 shadow-sm"><Search className="text-ink/40" size={18} /><input className="w-full bg-transparent text-sm outline-none" placeholder="Search name, email, or phone" value={search} onChange={(event) => setSearch(event.target.value)} /></div>
    <div className="mt-6 overflow-hidden rounded-3xl bg-white shadow-sm"><div className="hidden grid-cols-[1.4fr_1.1fr_1fr_.6fr_.8fr] gap-4 border-b border-black/5 px-5 py-4 text-xs font-bold uppercase tracking-wider text-ink/40 md:grid"><span>Customer</span><span>Contact</span><span>Membership</span><span>Bookings</span><span>Actions</span></div>{query.isLoading ? <div className="p-8 text-center text-sm text-ink/50">Loading customers…</div> : query.isError ? <div className="p-8 text-center text-sm text-red-700">Unable to load customers. <button className="font-semibold underline" onClick={() => void query.refetch()}>Try again</button></div> : query.data?.customers.length ? query.data.customers.map((customer) => <div key={customer.id} className="grid gap-3 border-b border-black/5 px-5 py-5 last:border-0 md:grid-cols-[1.4fr_1.1fr_1fr_.6fr_.8fr] md:items-center md:gap-4"><div><p className="font-semibold">{customer.firstName} {customer.lastName}</p><p className="text-sm text-ink/50">{customer.email}</p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-[10px] font-bold md:hidden ${customer.status === "ACTIVE" ? "bg-lime/60 text-pine" : "bg-red-50 text-red-700"}`}>{customer.status}</span></div><div className="text-sm text-ink/60">{customer.phone || "No phone"}</div><div className="text-sm text-ink/60">{customer.membership?.plan.name ?? "No active plan"}</div><div className="text-sm text-ink/60">{customer.bookingsCount}</div><div className="flex flex-wrap gap-3"><button className="text-sm font-semibold text-pine" onClick={() => editCustomer(customer)}><Pencil className="mr-1 inline" size={15} />Edit</button>{canDeactivate && customer.status === "ACTIVE" && <button className="text-sm font-semibold text-red-600" onClick={() => { if (window.confirm(`Deactivate ${customer.firstName} ${customer.lastName}? They will no longer be able to sign in.`)) void deactivate.mutateAsync(customer.id); }}><Trash2 className="mr-1 inline" size={15} />Deactivate</button>}</div></div>) : <div className="p-10 text-center text-sm text-ink/50">No customers match your search.</div>}</div>
    {open && <div className="fixed inset-0 z-40 grid place-items-center bg-ink/30 px-5"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-pine">Customer account</p><h2 className="mt-1 text-xl font-semibold">{editing ? "Edit customer" : "Register customer"}</h2></div><button type="button" aria-label="Close customer form" onClick={closeForm}><X /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{([['firstName','First name'],['lastName','Last name'],['email','Email'],['phone','Phone'],['address','Address']] as const).map(([field, label]) => <label key={field} className="text-sm font-medium">{label}<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type={field === "email" ? "email" : "text"} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} required={["firstName", "lastName", "email"].includes(field)} /></label>)}<label className="text-sm font-medium sm:col-span-2">{editing ? "New password (leave blank to keep current)" : "Temporary password"}<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="password" minLength={8} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required={!editing} /></label><label className="text-sm font-medium sm:col-span-2">Notes<textarea className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" rows={3} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={closeForm}>Cancel</Button><Button disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create customer"}</Button></div></form></div>}
  </div>;
}
