import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { PackageOpen, Pencil, Plus, RotateCcw } from "lucide-react";
import { useState } from "react";
import { Button } from "../components/Button";
import { apiFetch, ApiError } from "../lib/api";
import type { Equipment, EquipmentRental } from "../types";

const emptyForm = { name: "", quantity: "", availableQuantity: "", rentalPrice: "150", status: "ACTIVE" };

export function EquipmentManagement() {
  const client = useQueryClient();
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState(emptyForm);
  const query = useQuery({ queryKey: ["equipment", "manage"], queryFn: () => apiFetch<{ equipment: Equipment[] }>("/api/equipment/manage") });
  const rentals = useQuery({ queryKey: ["equipment-rentals", "manage"], queryFn: () => apiFetch<{ rentals: EquipmentRental[] }>("/api/equipment/rentals") });
  const save = useMutation({ mutationFn: () => apiFetch(editingId ? `/api/equipment/${editingId}` : "/api/equipment", { method: editingId ? "PATCH" : "POST", body: JSON.stringify({ name: form.name, quantity: Number(form.quantity), ...(editingId ? { availableQuantity: Number(form.availableQuantity) } : {}), rentalPrice: Number(form.rentalPrice), status: form.status }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["equipment"] }); setEditingId(null); setForm(emptyForm); setMessage("Equipment inventory saved."); } });
  const returnRental = useMutation({ mutationFn: (id: string) => apiFetch(`/api/equipment/rentals/${id}/return`, { method: "POST" }), onSuccess: () => { client.invalidateQueries({ queryKey: ["equipment"] }); client.invalidateQueries({ queryKey: ["equipment-rentals"] }); setError(""); setMessage("Equipment returned and inventory restored."); } });
  function edit(item: Equipment) { setEditingId(item.id); setForm({ name: item.name, quantity: String(item.quantity), availableQuantity: String(item.availableQuantity), rentalPrice: String(item.rentalPrice), status: item.status }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); if (editingId && Number(form.availableQuantity) > Number(form.quantity)) { setError("Available quantity cannot exceed total quantity."); return; } try { await save.mutateAsync(); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to save equipment."); } }

  return <div><div><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Equipment inventory</h1><p className="mt-2 text-ink/55">Manage rental quantities, returns, maintenance status, and pricing.</p></div>{message && <div className="mt-5 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <form onSubmit={submit} className="mt-6 grid gap-4 rounded-3xl bg-white p-6 md:grid-cols-2 xl:grid-cols-5"><div className="md:col-span-2 xl:col-span-5"><h2 className="text-lg font-semibold">{editingId ? "Update equipment" : "Add equipment"}</h2><p className="mt-1 text-xs text-ink/45">Use the rental return queue below to restore reserved stock automatically.</p></div><label className="text-sm font-medium">Equipment name<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label className="text-sm font-medium">Total quantity<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="0" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} required /></label>{editingId && <label className="text-sm font-medium">Available quantity<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="0" max={form.quantity} value={form.availableQuantity} onChange={(event) => setForm({ ...form, availableQuantity: event.target.value })} required /></label>}<label className="text-sm font-medium">Rental price<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="0" step="0.01" value={form.rentalPrice} onChange={(event) => setForm({ ...form, rentalPrice: event.target.value })} required /></label><label className="text-sm font-medium">Status<select className="mt-1.5 w-full rounded-xl border border-black/10 bg-white px-3 py-3" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="ACTIVE">Active</option><option value="MAINTENANCE">Maintenance</option><option value="INACTIVE">Inactive</option></select></label><div className="flex gap-2 md:col-span-2 xl:col-span-5"><Button disabled={save.isPending}>{save.isPending ? "Saving…" : editingId ? "Save changes" : "Add equipment"}</Button>{editingId && <Button type="button" variant="ghost" onClick={() => { setEditingId(null); setForm(emptyForm); }}>Cancel</Button>}</div></form>
    {query.isLoading ? <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">Loading equipment…</div> : query.isError ? <div className="mt-6 rounded-3xl bg-red-50 p-10 text-center text-sm text-red-700">Unable to load equipment.</div> : query.data?.equipment.length ? <div className="mt-6 grid gap-4 md:grid-cols-3">{query.data.equipment.map((item) => <div key={item.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-lime text-pine"><PackageOpen size={19} /></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.status === "ACTIVE" ? "bg-lime/60 text-pine" : "bg-amber-50 text-amber-700"}`}>{item.status}</span></div><h2 className="mt-4 font-semibold">{item.name}</h2><p className="mt-1 text-sm text-ink/50">₱{item.rentalPrice.toLocaleString()} rental</p><div className="mt-4 flex justify-between text-sm"><span>Available</span><span className="font-semibold">{item.availableQuantity}/{item.quantity}</span></div><button className="mt-4 text-sm font-semibold text-pine" onClick={() => edit(item)}><Pencil className="mr-1 inline" size={15} />Edit inventory</button></div>)}</div> : <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50"><Plus className="mx-auto mb-2 text-pine" />No equipment has been added.</div>}
    <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-pine">Return queue</p><h2 className="mt-1 text-xl font-semibold">Reserved equipment</h2></div>{rentals.isLoading ? <p className="mt-5 text-sm text-ink/50">Loading rentals…</p> : rentals.isError ? <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">Unable to load rental records.</p> : rentals.data?.rentals.filter((rental) => rental.status === "RESERVED").length ? <div className="mt-5 space-y-3">{rentals.data.rentals.filter((rental) => rental.status === "RESERVED").map((rental) => <div key={rental.id} className="flex flex-col justify-between gap-4 rounded-2xl bg-sand p-4 sm:flex-row sm:items-center"><div><p className="font-semibold">{rental.equipment.name} × {rental.quantity}</p><p className="mt-1 text-sm text-ink/50">{rental.customer.user.firstName} {rental.customer.user.lastName} · {new Date(rental.startsAt).toLocaleString("en-PH")}</p></div><Button className="shrink-0" disabled={returnRental.isPending} onClick={() => void returnRental.mutateAsync(rental.id).catch((exception) => setError(exception instanceof ApiError ? exception.message : "Unable to return equipment."))}><RotateCcw className="mr-1 inline" size={15} />Mark returned</Button></div>)}</div> : <p className="mt-5 rounded-xl bg-sand p-4 text-sm text-ink/50">No equipment is currently awaiting return.</p>}</section>
  </div>;
}
