import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { PackageOpen } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "../components/Button";
import { apiFetch, ApiError } from "../lib/api";
import type { Booking, Equipment as EquipmentType, EquipmentRental } from "../types";

export function Equipment() {
  const client = useQueryClient();
  const [equipmentId, setEquipmentId] = useState("");
  const [bookingId, setBookingId] = useState("");
  const [quantity, setQuantity] = useState("1");
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const equipment = useQuery({ queryKey: ["equipment"], queryFn: () => apiFetch<{ equipment: EquipmentType[] }>("/api/equipment") });
  const bookings = useQuery({ queryKey: ["bookings", "equipment"], queryFn: () => apiFetch<{ bookings: Booking[] }>("/api/bookings?limit=100") });
  const rentals = useQuery({ queryKey: ["equipment-rentals"], queryFn: () => apiFetch<{ rentals: EquipmentRental[] }>("/api/equipment/rentals") });
  const upcomingBookings = (bookings.data?.bookings ?? []).filter((booking) => ["PENDING", "CONFIRMED"].includes(booking.status) && new Date(booking.endsAt) > new Date()).sort((a, b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime());
  const selectedBooking = upcomingBookings.find((booking) => booking.id === bookingId);
  const rent = useMutation({ mutationFn: () => apiFetch("/api/equipment/rentals", { method: "POST", body: JSON.stringify({ equipmentId, bookingId, quantity: Number(quantity), startsAt: selectedBooking?.startsAt, endsAt: selectedBooking?.endsAt }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["equipment"] }); client.invalidateQueries({ queryKey: ["equipment-rentals"] }); setEquipmentId(""); setQuantity("1"); setMessage("Equipment reserved for your booking."); } });
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); try { await rent.mutateAsync(); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to rent equipment."); } }

  return <div><div><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Gear up</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Equipment rental</h1><p className="mt-2 text-ink/55">Add available equipment to one of your upcoming court bookings.</p></div>{message && <div className="mt-5 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {upcomingBookings.length ? <form onSubmit={submit} className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_120px_auto] lg:items-end"><label className="text-sm font-medium">Court booking<select className="mt-1.5 w-full rounded-xl border border-black/10 bg-white px-3 py-3" value={bookingId} onChange={(event) => setBookingId(event.target.value)} required><option value="">Choose booking</option>{upcomingBookings.map((booking) => <option key={booking.id} value={booking.id}>{booking.reference} · {booking.court.name} · {new Date(booking.startsAt).toLocaleString("en-PH")}</option>)}</select></label><label className="text-sm font-medium">Equipment<select className="mt-1.5 w-full rounded-xl border border-black/10 bg-white px-3 py-3" value={equipmentId} onChange={(event) => setEquipmentId(event.target.value)} required><option value="">Choose equipment</option>{equipment.data?.equipment.map((item) => <option key={item.id} value={item.id} disabled={item.availableQuantity < 1}>{item.name} · {item.availableQuantity} available</option>)}</select></label><label className="text-sm font-medium">Quantity<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="1" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><Button disabled={rent.isPending}>{rent.isPending ? "Reserving…" : "Reserve gear"}</Button></div></form> : <div className="mt-8 rounded-3xl bg-white p-8 text-center shadow-sm"><p className="font-semibold">Book a court before reserving equipment.</p><p className="mt-2 text-sm text-ink/50">Equipment must be tied to an upcoming reservation so the front desk knows when to prepare it.</p><Link className="mt-5 inline-block rounded-xl bg-pine px-4 py-3 text-sm font-semibold text-white" to="/app/book">Book a court</Link></div>}
    {equipment.isLoading ? <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">Loading equipment…</div> : equipment.isError ? <div className="mt-6 rounded-3xl bg-red-50 p-10 text-center text-sm text-red-700">Unable to load equipment.</div> : equipment.data?.equipment.length ? <div className="mt-6 grid gap-4 md:grid-cols-3">{equipment.data.equipment.map((item) => <div key={item.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="grid h-10 w-10 place-items-center rounded-xl bg-lime text-pine"><PackageOpen size={19} /></div><h2 className="mt-4 font-semibold">{item.name}</h2><p className="mt-1 text-sm text-ink/50">₱{item.rentalPrice.toLocaleString()} · {item.availableQuantity} available</p></div>)}</div> : <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">No equipment is currently available.</div>}
    <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">My rentals</h2>{rentals.isLoading ? <p className="mt-4 text-sm text-ink/50">Loading rentals…</p> : rentals.isError ? <p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">Unable to load rental history.</p> : rentals.data?.rentals.length ? <div className="mt-4 space-y-3">{rentals.data.rentals.map((rental) => <div key={rental.id} className="flex flex-col justify-between gap-2 rounded-2xl bg-sand p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{rental.equipment.name} × {rental.quantity}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${rental.status === "RESERVED" ? "bg-amber-50 text-amber-700" : rental.status === "RETURNED" ? "bg-lime/60 text-pine" : "bg-black/5 text-ink/45"}`}>{rental.status}</span></div><p className="text-sm text-ink/50">{new Date(rental.startsAt).toLocaleString("en-PH")}</p></div><p className="text-sm font-semibold">₱{(rental.unitPrice * rental.quantity).toLocaleString("en-PH")}</p></div>)}</div> : <p className="mt-4 text-sm text-ink/50">No equipment rentals yet.</p>}</section>
  </div>;
}
