import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Crown, Pencil, Plus, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../auth/AuthProvider";
import { Button } from "../components/Button";
import { ApiError, apiFetch } from "../lib/api";
import { usePublicSettings } from "../hooks/usePublicSettings";
import type { Membership, MembershipPlan } from "../types";

const paymentMethods = ["CASH", "BANK_TRANSFER", "GCASH", "CARD", "ONLINE_PAYMENT"] as const;
const emptyPlan = { name: "", description: "", price: "", durationDays: "30", discountPercent: "0", maximumBookings: "", benefits: "" };

export function Memberships() {
  const { user } = useAuth();
  const businessName = usePublicSettings().data?.businessName ?? "Rally Court Club";
  const navigate = useNavigate();
  const location = useLocation();
  const client = useQueryClient();
  const isPublicView = !location.pathname.startsWith("/app/");
  const isAdmin = !isPublicView && (user?.roles.some((role) => ["SUPER_ADMIN", "ADMIN"].includes(role)) ?? false);
  const isCustomer = !isPublicView && (user?.roles.includes("CUSTOMER") ?? false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [paymentMethod, setPaymentMethod] = useState<typeof paymentMethods[number]>("CASH");
  const [editing, setEditing] = useState<MembershipPlan | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState(emptyPlan);
  const plans = useQuery({ queryKey: ["membership-plans", isAdmin ? "manage" : "active"], queryFn: () => apiFetch<{ plans: MembershipPlan[] }>(isAdmin ? "/api/memberships" : "/api/memberships/plans") });
  const mine = useQuery({ queryKey: ["memberships", "me"], queryFn: () => apiFetch<{ memberships: Membership[] }>("/api/memberships/me"), enabled: isCustomer });
  const purchase = useMutation({ mutationFn: (planId: string) => apiFetch<{ membership: Membership }>("/api/memberships/purchase", { method: "POST", body: JSON.stringify({ planId, paymentMethod }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["memberships", "me"] }); client.invalidateQueries({ queryKey: ["payments"] }); setMessage("Membership selected. Staff will activate it after payment is confirmed."); } });
  const save = useMutation({ mutationFn: () => apiFetch(editing ? `/api/memberships/${editing.id}` : "/api/memberships", { method: editing ? "PUT" : "POST", body: JSON.stringify({ name: form.name, description: form.description, price: Number(form.price), durationDays: Number(form.durationDays), discountPercent: Number(form.discountPercent), maximumBookings: form.maximumBookings ? Number(form.maximumBookings) : editing ? null : undefined, benefits: form.benefits.split("\n").map((benefit) => benefit.trim()).filter(Boolean) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["membership-plans"] }); closePlanForm(); setMessage("Membership plan saved."); } });
  const toggle = useMutation({ mutationFn: (plan: MembershipPlan) => apiFetch(`/api/memberships/${plan.id}`, { method: "PUT", body: JSON.stringify({ isActive: !plan.isActive }) }), onSuccess: () => client.invalidateQueries({ queryKey: ["membership-plans"] }) });

  function closePlanForm() { setFormOpen(false); setEditing(null); setForm(emptyPlan); }
  function editPlan(plan: MembershipPlan) { setEditing(plan); setForm({ name: plan.name, description: plan.description ?? "", price: String(plan.price), durationDays: String(plan.durationDays), discountPercent: String(plan.discountPercent), maximumBookings: plan.maximumBookings ? String(plan.maximumBookings) : "", benefits: plan.benefits.join("\n") }); setFormOpen(true); }
  async function choose(planId: string) { if (isPublicView) { navigate(user ? "/app/memberships" : "/login", user ? undefined : { state: { from: "/app/memberships" } }); return; } if (!user) { navigate("/login", { state: { from: "/app/memberships" } }); return; } setError(""); setMessage(""); if (!window.confirm("Start this membership purchase? It will remain pending until payment is confirmed.")) return; try { await purchase.mutateAsync(planId); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to purchase membership."); } }
  async function submitPlan(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); try { await save.mutateAsync(); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to save membership plan."); } }

  if (isAdmin) return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Finance & growth</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Membership plans</h1><p className="mt-2 text-ink/55">Configure pricing, duration, discounts, booking limits, and customer benefits.</p></div><Button variant="secondary" onClick={() => { setEditing(null); setForm(emptyPlan); setFormOpen(true); }}><Plus className="mr-1 inline" size={16} />New plan</Button></div>
    {message && <div className="mt-5 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {plans.isLoading ? <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">Loading plans…</div> : plans.isError ? <div className="mt-6 rounded-3xl bg-red-50 p-10 text-center text-sm text-red-700">Unable to load membership plans.</div> : plans.data?.plans.length ? <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{plans.data.plans.map((plan) => <article key={plan.id} className="flex flex-col rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-pine">{plan.durationDays} days</p><h2 className="mt-1 text-2xl font-semibold">{plan.name}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${plan.isActive ? "bg-lime/60 text-pine" : "bg-black/5 text-ink/45"}`}>{plan.isActive ? "ACTIVE" : "INACTIVE"}</span></div><p className="mt-3 min-h-12 text-sm leading-6 text-ink/55">{plan.description || "No description."}</p><div className="mt-5 flex items-end justify-between"><p className="text-2xl font-semibold">₱{plan.price.toLocaleString("en-PH")}</p><p className="text-sm font-semibold text-pine">{plan.discountPercent}% court discount</p></div><div className="mt-5 flex-1 border-t border-black/5 pt-4"><p className="text-xs font-bold uppercase tracking-wider text-ink/40">Benefits</p><div className="mt-3 space-y-2">{plan.benefits.length ? plan.benefits.map((benefit) => <p key={benefit} className="text-sm text-ink/60"><Check className="mr-2 inline text-pine" size={15} />{benefit}</p>) : <p className="text-sm text-ink/45">No benefits listed.</p>}</div></div><div className="mt-6 flex gap-2"><Button className="flex-1" variant="ghost" onClick={() => editPlan(plan)}><Pencil className="mr-1 inline" size={15} />Edit</Button><Button className="flex-1" variant={plan.isActive ? "ghost" : "primary"} disabled={toggle.isPending} onClick={() => void toggle.mutateAsync(plan)}>{plan.isActive ? "Deactivate" : "Activate"}</Button></div></article>)}</div> : <div className="mt-6 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">No plans created yet.</div>}
    {formOpen && <div className="fixed inset-0 z-40 grid place-items-center bg-ink/30 px-5"><form onSubmit={submitPlan} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-pine">Plan configuration</p><h2 className="mt-1 text-xl font-semibold">{editing ? `Edit ${editing.name}` : "New membership plan"}</h2></div><button type="button" aria-label="Close plan form" onClick={closePlanForm}><X /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Name<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label className="text-sm font-medium">Price (PHP)<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="0" step="0.01" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} required /></label><label className="text-sm font-medium">Duration (days)<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="1" value={form.durationDays} onChange={(event) => setForm({ ...form, durationDays: event.target.value })} required /></label><label className="text-sm font-medium">Court discount (%)<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="0" max="100" value={form.discountPercent} onChange={(event) => setForm({ ...form, discountPercent: event.target.value })} required /></label><label className="text-sm font-medium">Maximum bookings (optional)<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="number" min="1" value={form.maximumBookings} onChange={(event) => setForm({ ...form, maximumBookings: event.target.value })} /></label><label className="text-sm font-medium sm:col-span-2">Description<textarea className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" rows={2} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label className="text-sm font-medium sm:col-span-2">Benefits (one per line)<textarea className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" rows={6} value={form.benefits} onChange={(event) => setForm({ ...form, benefits: event.target.value })} placeholder={"Priority booking\n10% court discount\nMember booking history"} /></label></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={closePlanForm}>Cancel</Button><Button disabled={save.isPending}>{save.isPending ? "Saving…" : "Save plan"}</Button></div></form></div>}
  </div>;

  const active = isPublicView ? undefined : mine.data?.memberships.find((membership) => membership.status === "ACTIVE");
  const pending = isPublicView ? undefined : mine.data?.memberships.find((membership) => membership.status === "PENDING");
  return <main className="-mx-5 bg-sand px-5 pb-16 pt-8 lg:-mx-8 lg:px-8"><div className="mx-auto max-w-7xl"><section className="relative overflow-hidden rounded-[2rem] bg-pine px-6 py-10 text-white shadow-soft sm:px-10 lg:px-14 lg:py-14"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-lime/20 blur-3xl" /><div className="relative max-w-2xl"><div className="inline-flex items-center gap-2 rounded-full bg-lime/20 px-3 py-1.5 text-xs font-bold uppercase tracking-[.18em] text-lime"><Sparkles size={14} /> Club membership</div><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-5xl">Choose how you play.</h1><p className="mt-4 max-w-xl text-base leading-7 text-white/70 sm:text-lg">Unlock better value, priority access, and more time on the court with a {businessName} membership.</p></div></section>
    {(active || pending) && <section className="relative z-10 mx-4 -mt-7 rounded-2xl border border-white/60 bg-white p-5 shadow-lg sm:mx-8 sm:flex sm:items-center sm:justify-between sm:px-7"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-pine">{active ? "Current membership" : "Pending membership"}</p><h2 className="mt-1 text-xl font-semibold">{(active ?? pending)?.plan.name}</h2><p className="mt-1 text-sm text-ink/55">{active ? `${active.plan.discountPercent}% court discount · ends ${new Date(active.endDate).toLocaleDateString("en-PH")}` : "Awaiting payment confirmation from the front desk."}</p></div><span className={`mt-4 inline-flex rounded-full px-3 py-1.5 text-xs font-bold sm:mt-0 ${active ? "bg-lime/60 text-pine" : "bg-amber-50 text-amber-700"}`}>{active ? "ACTIVE" : "PENDING"}</span></section>}
    {message && <div className="mt-6 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-6 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <div className="mt-12 text-center"><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Simple plans</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">More play. More value.</h2><p className="mx-auto mt-3 max-w-xl text-ink/55">Every plan includes clear benefits that are applied automatically after activation.</p></div>
    {!isPublicView && user && <label className="mx-auto mt-6 block max-w-sm text-sm font-medium">Preferred payment method<select className="mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-3" value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value as typeof paymentMethods[number])}>{paymentMethods.map((method) => <option key={method} value={method}>{method.replaceAll("_", " ")}</option>)}</select><span className="mt-2 block text-xs font-normal text-ink/45">No online charge occurs yet. Staff verifies the payment before activation.</span></label>}
    {plans.isLoading ? <div className="mt-8 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">Loading membership plans…</div> : plans.isError ? <div className="mt-8 rounded-3xl bg-white p-10 text-center text-sm text-red-700">Unable to load membership plans. Please try again.</div> : plans.data?.plans.length ? <div className="mt-8 grid items-stretch gap-5 md:grid-cols-2 xl:grid-cols-4">{plans.data.plans.map((plan, index) => <article key={plan.id} className={`relative flex h-full flex-col rounded-3xl border p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg ${index === 2 ? "border-pine bg-pine text-white" : "border-black/5 bg-white"}`}>{index === 2 && <span className="absolute -top-3 left-6 rounded-full bg-lime px-3 py-1 text-xs font-bold text-pine">MOST POPULAR</span>}<div className="flex items-center justify-between"><div className={`grid h-11 w-11 place-items-center rounded-xl ${index === 2 ? "bg-lime text-pine" : "bg-lime/60 text-pine"}`}><Crown size={20} /></div><span className={`text-xs font-bold ${index === 2 ? "text-white/65" : "text-pine"}`}>{plan.durationDays} days</span></div><h3 className="mt-6 text-2xl font-semibold">{plan.name}</h3><p className={`mt-2 min-h-12 text-sm leading-6 ${index === 2 ? "text-white/65" : "text-ink/55"}`}>{plan.description || "A flexible way to enjoy the club."}</p><div className="mt-6"><span className="text-3xl font-semibold">₱{plan.price.toLocaleString("en-PH")}</span><span className={`ml-1 text-sm ${index === 2 ? "text-white/55" : "text-ink/45"}`}>/ plan</span></div><div className={`mt-5 flex-1 border-t pt-5 text-sm ${index === 2 ? "border-white/15 text-white/75" : "border-black/5 text-ink/65"}`}><p className="font-semibold">Plan benefits</p><div className="mt-4 space-y-3">{(plan.benefits.length ? plan.benefits : ["Book courts online", `${plan.discountPercent}% court discount`]).map((benefit) => <p key={benefit}><Check className={`mr-2 inline ${index === 2 ? "text-lime" : "text-pine"}`} size={16} />{benefit}</p>)}</div></div><Button className={`mt-7 w-full ${index === 2 ? "bg-lime text-pine hover:bg-[#cbed3f]" : ""}`} disabled={!isPublicView && (purchase.isPending || Boolean(active || pending))} onClick={() => void choose(plan.id)}>{isPublicView ? user ? "Open my membership" : "Join to choose" : active ? "Membership active" : pending ? "Payment pending" : purchase.isPending ? "Processing…" : "Choose plan"}</Button></article>)}</div> : <div className="mt-8 rounded-3xl bg-white p-10 text-center text-sm text-ink/50">No membership plans are currently available.</div>}
    <p className="mx-auto mt-8 max-w-2xl text-center text-xs leading-5 text-ink/45">{isPublicView ? "Sign in to select a plan and review your membership status securely in your account." : "Membership purchases remain pending until payment is confirmed by authorized staff."}</p>
  </div></main>;
}
