import { useQuery } from "@tanstack/react-query";
import { Mail, MapPin, Phone, ShieldCheck, Trophy } from "lucide-react";
import { apiFetch } from "../lib/api";
import type { Coach } from "../types";
import { usePublicSettings } from "../hooks/usePublicSettings";

export function About() { const settings = usePublicSettings().data; const businessName = settings?.businessName ?? "Rally Court Club"; return <main className="bg-sand px-5 py-16 lg:px-8"><div className="mx-auto max-w-4xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">About {businessName}</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">A better place to play, learn, and belong.</h1><p className="mt-6 text-lg leading-8 text-ink/60">{businessName} is a pickleball destination built around great courts, friendly service, and a community that keeps showing up.</p><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="rounded-3xl bg-pine p-6 text-white"><Trophy size={22} /><h2 className="mt-5 font-semibold">Quality courts</h2><p className="mt-2 text-sm text-white/65">Reliable surfaces, clear availability, and a smooth booking experience.</p></div><div className="rounded-3xl bg-lime p-6 text-pine"><ShieldCheck size={22} /><h2 className="mt-5 font-semibold">Easy to join</h2><p className="mt-2 text-sm text-pine/65">Book by the hour, choose a membership, or work with a coach.</p></div><div className="rounded-3xl bg-white p-6"><MapPin size={22} className="text-pine" /><h2 className="mt-5 font-semibold">Your home court</h2><p className="mt-2 text-sm text-ink/60">{settings?.address || "A welcoming venue for early mornings and after-work rallies."}</p></div></div></div></main>; }

export function Contact() { const settings = usePublicSettings().data; return <main className="bg-sand px-5 py-16 lg:px-8"><div className="mx-auto max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Contact</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">Let’s get you on court.</h1><p className="mt-5 text-lg leading-8 text-ink/60">Questions about bookings, memberships, coaching, or venue availability? Our front desk team can help.</p><div className="mt-10 grid gap-4 sm:grid-cols-3">{settings?.email ? <a className="rounded-2xl bg-white p-5 shadow-sm" href={`mailto:${settings.email}`}><Mail className="text-pine" size={20} /><p className="mt-4 font-semibold">Email</p><p className="mt-1 break-all text-sm text-ink/55">{settings.email}</p></a> : <div className="rounded-2xl bg-white p-5 shadow-sm"><Mail className="text-pine" size={20} /><p className="mt-4 font-semibold">Email</p><p className="mt-1 text-sm text-ink/55">Contact details coming soon</p></div>}{settings?.phone ? <a className="rounded-2xl bg-white p-5 shadow-sm" href={`tel:${settings.phone}`}><Phone className="text-pine" size={20} /><p className="mt-4 font-semibold">Phone</p><p className="mt-1 text-sm text-ink/55">{settings.phone}</p></a> : <div className="rounded-2xl bg-white p-5 shadow-sm"><Phone className="text-pine" size={20} /><p className="mt-4 font-semibold">Phone</p><p className="mt-1 text-sm text-ink/55">Contact details coming soon</p></div>}<div className="rounded-2xl bg-white p-5 shadow-sm"><MapPin className="text-pine" size={20} /><p className="mt-4 font-semibold">Location</p><p className="mt-1 text-sm text-ink/55">{settings?.address ?? "Metro Manila, Philippines"}</p></div></div><p className="mt-6 text-center text-sm text-ink/50">{settings?.businessHours ?? "Daily 6:00 AM–10:00 PM"}</p></div></main>; }

export function FAQ() { const questions = [["How do I book a court?", "Create an account, choose a court and time, then confirm your booking from the booking page."], ["Can I cancel my booking?", "Yes. Cancellation timing follows the business rules shown in your account and booking flow."], ["Do you offer coaching?", "Yes. Browse available coaches and request a session from the Coaching area after signing in."], ["Can I rent equipment?", "Yes. Paddles and other available equipment can be rented from the Equipment area."]]; return <main className="bg-sand px-5 py-16 lg:px-8"><div className="mx-auto max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">FAQ</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">Good questions. Better rallies.</h1><div className="mt-10 space-y-3">{questions.map(([question, answer]) => <details key={question} className="rounded-2xl bg-white p-5 shadow-sm"><summary className="cursor-pointer font-semibold">{question}</summary><p className="mt-3 text-sm leading-6 text-ink/60">{answer}</p></details>)}</div></div></main>; }

export function PublicCoaches() { const query = useQuery({ queryKey: ["public-coaches"], queryFn: () => apiFetch<{ coaches: Coach[] }>("/api/coaching/coaches") }); return <main className="bg-sand px-5 py-16 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Coaching</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">Learn from coaches who love the game.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-ink/60">Build confidence, improve your fundamentals, and make every rally more intentional.</p>{query.isLoading ? <div className="mt-10 rounded-3xl bg-white p-8 text-center text-ink/50">Loading coaches…</div> : query.isError ? <div className="mt-10 rounded-3xl bg-red-50 p-8 text-center text-red-700">Unable to load coaches right now. <button type="button" className="font-semibold underline" onClick={() => void query.refetch()}>Try again</button></div> : query.data?.coaches.length ? <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{query.data.coaches.map((coach) => <article key={coach.id} className="rounded-3xl bg-white p-6 shadow-sm"><div className="grid h-14 w-14 place-items-center rounded-full bg-lime text-xl font-semibold text-pine">{coach.user.firstName[0]}{coach.user.lastName[0]}</div><h2 className="mt-5 text-xl font-semibold">{coach.user.firstName} {coach.user.lastName}</h2><p className="mt-1 text-sm text-ink/50">₱{coach.hourlyRate.toLocaleString()}/hour</p><p className="mt-4 text-sm leading-6 text-ink/60">{coach.biography || "Coach profile coming soon."}</p></article>)}</div> : <div className="mt-10 rounded-3xl bg-white p-8 text-center text-ink/50">No coaches are available right now. Please check again soon.</div>}</div></main>; }
