import { useQuery } from "@tanstack/react-query";
import { ArrowRight, CalendarDays, Coins, Gauge, PackageCheck, Trophy, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";
import type { League, OpenPlay, PackagePlan } from "../types";

const money = (value: number) => `₱${value.toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;
const dateTime = (value: string) => new Date(value).toLocaleString("en-PH", { dateStyle: "medium", timeStyle: "short" });

export function PublicPlay() {
  const openPlays = useQuery({ queryKey: ["public-open-plays"], queryFn: () => apiFetch<{ openPlays: OpenPlay[] }>("/api/growth/open-plays") });
  const leagues = useQuery({ queryKey: ["public-leagues"], queryFn: () => apiFetch<{ leagues: League[] }>("/api/growth/leagues") });
  const packages = useQuery({ queryKey: ["public-packages"], queryFn: () => apiFetch<{ packages: PackagePlan[] }>("/api/growth/packages") });
  const loading = openPlays.isLoading || leagues.isLoading || packages.isLoading;
  const failed = openPlays.isError || leagues.isError || packages.isError;

  return <main className="bg-sand">
    <section className="overflow-hidden bg-pine px-5 py-16 text-white lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-lime">Play more, organize less</p><h1 className="mt-4 max-w-3xl text-5xl font-semibold tracking-tight sm:text-6xl">Walk in solo. Leave with a game.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/65">Join skill-matched open play, enter a club ladder, or reserve a court without creating an account first.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/guest-book" className="rounded-xl bg-lime px-5 py-3 font-semibold text-pine">Book as a guest <ArrowRight className="ml-1 inline" size={17} /></Link><Link to="/register" className="rounded-xl border border-white/20 px-5 py-3 font-semibold text-white">Create a player profile</Link></div></div><div className="grid grid-cols-2 gap-3"><Feature icon={Users} label="Skill-matched" value="Open play" /><Feature icon={Gauge} label="Local rating" value="1.0–8.0" /><Feature icon={Trophy} label="Competitive" value="Ladders" /><Feature icon={Coins} label="Faster checkout" value="Club wallet" /></div></div></section>
    <div className="mx-auto max-w-7xl px-5 py-14 lg:px-8">
      {loading && <State text="Loading current club programs…" />}
      {failed && <State error text="Current programs could not be loaded. Please try again shortly." />}
      {!loading && !failed && <div className="space-y-14">
        <section><Heading eyebrow="Find your game" title="Upcoming open play" text="Pay for one player spot instead of organizing an entire group and court." /><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{openPlays.data?.openPlays.length ? openPlays.data.openPlays.map((play) => <article key={play.id} className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-lime text-pine"><Users size={20} /></div><span className="rounded-full bg-sand px-3 py-1 text-xs font-bold text-ink/55">{play.participants.length}/{play.capacity} joined</span></div><h3 className="mt-5 text-xl font-semibold">{play.title}</h3><p className="mt-2 text-sm text-ink/50">{play.court.name} · {dateTime(play.startsAt)}</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-sand px-2.5 py-1">Rating {play.skillMin.toFixed(1)}–{play.skillMax.toFixed(1)}</span><span className="rounded-full bg-sand px-2.5 py-1">{play.competitive ? "Competitive" : "Social"}</span></div><div className="mt-6 flex items-center justify-between"><strong>{money(play.pricePerPlayer)}</strong><Link to="/register" className="text-sm font-semibold text-pine">Join as a member →</Link></div></article>) : <State text="The next open-play schedule will appear here." />}</div></section>
        <section><Heading eyebrow="Club competition" title="Leagues and ladders" text="Build a verified local playing history with standings and rating updates after every recorded match." /><div className="mt-7 grid gap-5 md:grid-cols-2">{leagues.data?.leagues.length ? leagues.data.leagues.map((league) => <article key={league.id} className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><Trophy className="text-pine" /><span className="rounded-full bg-lime/50 px-3 py-1 text-xs font-bold text-pine">{league.status.replaceAll("_", " ")}</span></div><h3 className="mt-5 text-2xl font-semibold">{league.name}</h3><p className="mt-3 text-sm leading-6 text-ink/55">{league.description}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-sand p-3"><p className="text-xs text-ink/40">Division</p><p className="mt-1 font-semibold">{league.skillMin.toFixed(1)}–{league.skillMax.toFixed(1)}</p></div><div className="rounded-xl bg-sand p-3"><p className="text-xs text-ink/40">Entry fee</p><p className="mt-1 font-semibold">{money(league.entryFee)}</p></div></div></article>) : <State text="No league registration is open right now." />}</div></section>
        <section><Heading eyebrow="Save on repeat play" title="Prepaid booking packages" text="Buy booking credits, skip payment approval at checkout, and receive your access pass immediately." /><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{packages.data?.packages.map((plan) => <article key={plan.id} className="flex flex-col rounded-3xl bg-white p-6 shadow-sm"><PackageCheck className="text-pine" /><h3 className="mt-5 text-xl font-semibold">{plan.name}</h3><p className="mt-2 flex-1 text-sm leading-6 text-ink/50">{plan.description}</p><p className="mt-5 text-3xl font-semibold">{money(plan.price)}</p><p className="mt-1 text-xs text-ink/45">{plan.bookingCredits} bookings · valid {plan.validityDays} days</p><Link to="/register" className="mt-5 rounded-xl bg-pine px-4 py-3 text-center text-sm font-semibold text-white">Join and purchase</Link></article>)}</div></section>
      </div>}
    </div>
  </main>;
}

function Feature({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string }) { return <div className="rounded-2xl bg-white/10 p-4"><Icon className="text-lime" size={20} /><p className="mt-5 text-xs text-white/50">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.16em] text-pine">{eyebrow}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h2><p className="mt-3 leading-7 text-ink/55">{text}</p></div>; }
function State({ text, error = false }: { text: string; error?: boolean }) { return <div className={`col-span-full rounded-3xl p-10 text-center text-sm ${error ? "bg-red-50 text-red-700" : "bg-white text-ink/50"}`}><CalendarDays className="mx-auto mb-3" size={22} />{text}</div>; }
