import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, UserCog, X } from "lucide-react";
import { useState } from "react";
import { useAuth } from "../auth/AuthProvider";
import { Button } from "../components/Button";
import { apiFetch, ApiError } from "../lib/api";
import type { AdminUser, Role } from "../types";

const empty = { email: "", firstName: "", lastName: "", phone: "", password: "", role: "STAFF" as Role };

export function UserManagement() {
  const { user } = useAuth();
  const client = useQueryClient();
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState(empty);
  const query = useQuery({ queryKey: ["admin-users"], queryFn: () => apiFetch<{ users: AdminUser[] }>("/api/admin/users") });
  const create = useMutation({ mutationFn: () => apiFetch("/api/admin/users", { method: "POST", body: JSON.stringify(form) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin-users"] }); setOpen(false); setForm(empty); setMessage("User account created."); } });
  const update = useMutation({ mutationFn: ({ id, status, roles }: { id: string; status?: string; roles?: Role[] }) => apiFetch(`/api/admin/users/${id}`, { method: "PATCH", body: JSON.stringify({ status, roles }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin-users"] }); setMessage("User access updated."); } });
  const isSuperAdmin = user?.roles.includes("SUPER_ADMIN") ?? false;
  async function updateUser(id: string, change: { status?: string; roles?: Role[] }) { setError(""); setMessage(""); try { await update.mutateAsync({ id, ...change }); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to update user."); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); try { await create.mutateAsync(); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to create user."); } }

  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-pine">Administration</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Users & access</h1><p className="mt-2 text-ink/55">Create staff accounts, assign roles, and control account access.</p></div><Button variant="secondary" onClick={() => setOpen(true)}><Plus className="mr-1 inline" size={16} />New user</Button></div>
    {message && <div className="mt-5 rounded-xl bg-lime/50 px-4 py-3 text-sm text-pine">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <div className="mt-6 overflow-hidden rounded-3xl bg-white shadow-sm"><div className="hidden grid-cols-[1.4fr_1fr_.9fr_1fr] gap-4 border-b border-black/5 px-5 py-4 text-xs font-bold uppercase tracking-wider text-ink/40 md:grid"><span>User</span><span>Profile</span><span>Role</span><span>Status</span></div>{query.isLoading ? <div className="p-10 text-center text-sm text-ink/50">Loading users…</div> : query.isError ? <div className="p-10 text-center text-sm text-red-700">Unable to load users.</div> : query.data?.users.length ? query.data.users.map((account) => { const protectedAccount = account.roles.includes("SUPER_ADMIN") && !isSuperAdmin; const primaryRole = account.roles[0] ?? "CUSTOMER"; return <div key={account.id} className="grid gap-3 border-b border-black/5 px-5 py-5 last:border-0 md:grid-cols-[1.4fr_1fr_.9fr_1fr] md:items-center md:gap-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-lime text-pine"><UserCog size={18} /></div><div className="min-w-0"><p className="truncate font-semibold">{account.firstName} {account.lastName}</p><p className="truncate text-sm text-ink/50">{account.email}</p></div></div><div className="text-sm text-ink/60">{account.profile ?? "Administrative account"}</div><div>{protectedAccount ? <span className="rounded-full bg-sand px-2 py-1 text-[11px] font-bold">SUPER ADMIN</span> : <select aria-label={`Role for ${account.email}`} className="rounded-lg border border-black/10 bg-white px-2 py-2 text-xs" value={primaryRole} onChange={(event) => void updateUser(account.id, { roles: [event.target.value as Role] })} disabled={update.isPending}><option value="CUSTOMER">Customer</option><option value="COACH">Coach</option><option value="STAFF">Staff</option><option value="ADMIN">Admin</option>{isSuperAdmin && <option value="SUPER_ADMIN">Super Admin</option>}</select>}</div><div className="flex items-center justify-between gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${account.status === "ACTIVE" ? "bg-lime/60 text-pine" : "bg-red-50 text-red-700"}`}>{account.status}</span>{!protectedAccount && <select aria-label={`Status for ${account.email}`} className="rounded-lg border border-black/10 bg-white px-2 py-2 text-xs" value={account.status} onChange={(event) => void updateUser(account.id, { status: event.target.value })} disabled={update.isPending}><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option><option value="DEACTIVATED">Deactivated</option></select>}</div></div>; }) : <div className="p-10 text-center text-sm text-ink/50">No users found.</div>}</div>
    {open && <div className="fixed inset-0 z-40 grid place-items-center bg-ink/30 px-5"><form onSubmit={submit} className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-pine">Account setup</p><h2 className="mt-1 text-xl font-semibold">Create user</h2></div><button type="button" aria-label="Close user form" onClick={() => setOpen(false)}><X /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">First name<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.firstName} onChange={(event) => setForm({ ...form, firstName: event.target.value })} required /></label><label className="text-sm font-medium">Last name<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.lastName} onChange={(event) => setForm({ ...form, lastName: event.target.value })} required /></label><label className="text-sm font-medium">Email<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><label className="text-sm font-medium">Phone<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label className="text-sm font-medium">Temporary password<input className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3" type="password" minLength={8} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /></label><label className="text-sm font-medium">Role<select className="mt-1.5 w-full rounded-xl border border-black/10 bg-white px-3 py-3" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as Role })}><option value="STAFF">Staff</option><option value="COACH">Coach</option><option value="ADMIN">Admin</option><option value="CUSTOMER">Customer</option>{isSuperAdmin && <option value="SUPER_ADMIN">Super Admin</option>}</select></label></div><p className="mt-4 text-xs text-ink/45">Share the temporary password securely and require the user to change it from Profile after first sign-in.</p><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={create.isPending}>{create.isPending ? "Creating…" : "Create user"}</Button></div></form></div>}
  </div>;
}
