import { useEffect } from "react";
import { Link, Outlet } from "react-router-dom";
import { Logo } from "../components/Logo";
import { usePublicSettings } from "../hooks/usePublicSettings";

const links = [{ to: "/play", label: "Play & leagues" }, { to: "/events", label: "Events" }, { to: "/courts", label: "Courts" }, { to: "/memberships", label: "Memberships" }, { to: "/coaches", label: "Coaches" }, { to: "/contact", label: "Contact" }, { to: "/faq", label: "FAQ" }];

export function PublicLayout() {
  const settings = usePublicSettings().data;
  const businessName = settings?.businessName ?? "Rally Court Club";
  useEffect(() => { document.title = businessName; }, [businessName]);
  return <div className="min-h-screen bg-white text-ink"><header className="border-b border-black/5 bg-white/95"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link to="/"><Logo businessName={businessName} logoUrl={settings?.logoUrl} /></Link><nav className="hidden items-center gap-5 text-sm text-ink/70 lg:flex">{links.map((link) => <Link key={link.to} className="transition hover:text-pine" to={link.to}>{link.label}</Link>)}</nav><div className="flex items-center gap-1.5 sm:gap-2"><Link className="rounded-xl px-2.5 py-2 text-sm font-semibold text-ink/70 hover:bg-sand sm:px-3" to="/login">Sign in</Link><Link className="hidden rounded-xl px-3 py-2.5 text-sm font-semibold text-pine hover:bg-sand sm:block" to="/register">Join</Link><Link className="rounded-xl bg-pine px-3 py-2.5 text-sm font-semibold text-white sm:px-4" to="/guest-book">Book now</Link></div></div><nav className="mx-auto flex max-w-7xl gap-4 overflow-x-auto border-t border-black/5 px-5 py-3 text-xs font-semibold text-ink/60 lg:hidden">{links.map((link) => <Link key={link.to} className="shrink-0 hover:text-pine" to={link.to}>{link.label}</Link>)}</nav></header><Outlet /><footer className="border-t border-black/5 bg-white px-5 py-10 text-sm text-ink/50"><div className="mx-auto grid max-w-7xl gap-8 sm:grid-cols-2 lg:grid-cols-4"><div><Link to="/"><Logo businessName={businessName} logoUrl={settings?.logoUrl} /></Link><p className="mt-4 max-w-xs leading-6">Premium courts, better rallies, and a welcoming pickleball community.</p></div><div><p className="font-bold uppercase tracking-[.16em] text-pine">Explore</p><div className="mt-4 space-y-2.5">{links.slice(0, 3).map((link) => <Link key={link.to} className="block hover:text-pine" to={link.to}>{link.label}</Link>)}</div></div><div><p className="font-bold uppercase tracking-[.16em] text-pine">Help</p><div className="mt-4 space-y-2.5"><Link className="block hover:text-pine" to="/contact">Contact us</Link><Link className="block hover:text-pine" to="/faq">Frequently asked questions</Link><Link className="block hover:text-pine" to="/about">About the club</Link></div></div><div><p className="font-bold uppercase tracking-[.16em] text-pine">Visit</p><p className="mt-4 leading-6">{settings?.address ?? "Metro Manila, Philippines"}<br />{settings?.businessHours ?? "Daily 6:00 AM–10:00 PM"}</p>{settings?.phone && <a className="mt-2 block hover:text-pine" href={`tel:${settings.phone}`}>{settings.phone}</a>}</div></div><div className="mx-auto mt-8 flex max-w-7xl flex-col justify-between gap-3 border-t border-black/5 pt-6 text-xs sm:flex-row"><span>© {new Date().getFullYear()} {businessName}</span><span>Premium courts. Better rallies.</span></div></footer></div>;
}
